# @package _global_

# specify here default sim configuration
defaults:
  - _self_

  - mode: default.yaml

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ../data_gen/data #${hydra:runtime.cwd}

# path to folder with data
data_dir: data
upload: false

output_path: 2D_diff-react_r100_all
nsample: 100

# name of the run, accessed by loggers
name: 2D_diff-react_r100_diff
sim:
  Du: 1E-3
  Dv: 1E-1
  k: 5E-3
  t: 5
  tdim: 101
  x_left: -1.0
  x_right: 1.0
  xdim: 128
  y_bottom: -1.0
  y_top: 1.0
  ydim: 128
  n: 1
  seed: "???"
  sim_type: "diff"

plot:
  t_idx: 1.00 # Fraction of the final time step idx to be plotted
  dim: 2 # Spatial dimension
  channel_idx: 0 # Index of the variable to be plotted

